### ISSUE TITLE
Export to image

### ISSUE THREAD

**Issue by alesshosry** [jsreport/jsreport-dotnet-example-webapp#3]
Thank you for the template, is it possible to download as image? I have changed the code of invoiceDownload to this:

```
HttpContext.JsReportFeature().Recipe(Recipe.PhantomImage)
                .OnAfterRender((r) => HttpContext.Response.Headers["Content-Disposition"] = "image; filename=\"myReport.jpeg\"");

            return View("Invoice", InvoiceModel.Example());
```
But an error was thrown as you can see  
 
![jsreporterror](https://user-images.githubusercontent.com/26387399/38352160-ef028394-38ba-11e8-96cb-64c316d28efa.png)

**Comment by pofider** [comment]
With deeper look to the error message, you should see error "recipe phantom-image was not found".
This is because the `jsreport-phantom-image" is not part of the compiled `jsreport.exe` which is bundled in `jsreport.Local.`. This jsreport version includes only default extensions. The custom ones needs to be installed. See here

https://jsreport.net/learn/dotnet-local#custom-extensions

**Comment by alesshosry** [comment]
Thank you for your reply, so you're saying that it can be converted to image but I have to download first the extension? I am asking this question because I didn't see in your documentation that reports can be converted to images, I saw pdf, Excel, html ... But not image. Please I need a clear answer, Thank you

**Comment by pofider** [comment]
Yes, 
You can see the list of recipes [here](https://jsreport.net/learn/recipes). The github icon marks it as custom and needs to be installed separately. One of them is `phantom-image`.

**Comment by AlessHo** [comment]
Ok finally I did it and I'm very glad...
I am using jsreport in my .NETCore 2 API and I have created a special controller that returns views to the client as PDF or Images; 
Now my question is the below:
How can I download the pdf and images on my server? In other words, how can I  ** specify the filePath where the report should be downloaded on my webserver instead of user's PC **? Below is my code, thank you

```
[MiddlewareFilter(typeof(JsReportPipeline))]
[HttpGet("Imagedownload")]

public IActionResult ImageDownload()
    {
      HttpContext.JsReportFeature().Recipe(Recipe.PhantomImage)
               .OnAfterRender((r) => HttpContext.Response.Headers["Content-Disposition"] = "image; filename=\"myImage.png\"");  

     // instead of downloading image on user's PC it should be downloaded on my webserver... and then I will return a response to the user; Is it possible?
      
      var dp = new Classes.DataProvider();
      var lstnames = dp.GetRegisteredNames();
      var lst = lstnames.ToArray<string>();
      return View("Users", lst);
    }
```
